project_name: qlc-hub
env:
  - GO111MODULE=on
#  - GOPROXY=https://goproxy.cn,direct
before:
  hooks:
  # you may remove this if you don't use vgo
  #    - go mod download
  # you may remove this if you don't need go generate
  # - go generate ./...
builds:
  - id: ghub-darwin
    ldflags: -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    binary: ghub
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    main: ./cmd/main.go
    goos:
      - darwin
    goarch:
      - amd64
  - id: ghub-linux
    ldflags: -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    binary: ghub
    env:
      - CGO_ENABLED=1
    main: ./cmd/main.go
    goos:
      - linux
    goarch:
      - amd64
  - id: ghub-windows-x64
    ldflags: main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    binary: ghub
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    main: ./cmd/main.go
    goos:
      - windows
    goarch:
      - amd64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}-v{{ .Version }}-{{ .ShortCommit }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      amd64: x64
      386: i386
      darwin: macOS
      linux: Linux
      windows: Windows
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

signs:
  -
    # name of the signature file.
    # '${artifact}' is the path to the artifact that should be signed.
    #
    # defaults to `${artifact}.sig`
    # signature: "${artifact}_sig"

    # command line arguments for the command
    #
    # to sign with a specific key use
    # args: ["-u", "<key id, fingerprint, email, ..>", "--output", "${signature}", "--detach-sign", "${artifact}"]
    #
    # defaults to `["--output", "${signature}", "--detach-sign", "${artifact}"]`
    args: ["-u", "QLCChain Bot (qlcchain-bot) <developers@qlink.mobi>", "--output", "${signature}", "--detach-sign", "${artifact}"]

    # which artifacts to sign
    #
    #   checksum: only checksum file(s)
    #   all:      all artifacts
    #   none:     no signing
    #
    # defaults to `none`
    artifacts: all

release:
  github:
    owner: qlcchain
    name: qlc-hub

  prerelease: auto
