FROM golang:1.15.7-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git

COPY . /qlcchain/qlc-hub
RUN cd /qlcchain/qlc-hub && make clean signer

FROM alpine:3.12.1
LABEL maintainer="developers@qlink.mobi"

ENV QLCCHAIN /qlcchain

RUN apk --no-cache add ca-certificates && \
    addgroup qlcchain && \
    adduser -S -G qlcchain qlcchain -s /bin/sh -h "$QLCCHAIN" && \
    chown -R qlcchain:qlcchain "$QLCCHAIN"

USER qlcchain

WORKDIR $QLCCHAIN

COPY --from=builder /qlcchain/qlc-hub/build/signer /usr/local/bin/signer

ENTRYPOINT [ "signer"]

