package types

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *LockerInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			return
		}
		switch msgp.UnsafeString(field) {
		case "state":
			err = z.State.DecodeMsg(dc)
			if err != nil {
				return
			}
		case "rHash":
			z.RHash, err = dc.ReadString()
			if err != nil {
				return
			}
		case "rOrigin":
			z.ROrigin, err = dc.ReadString()
			if err != nil {
				return
			}
		case "amount":
			z.Amount, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "lnHash":
			z.LockedNeoHash, err = dc.ReadString()
			if err != nil {
				return
			}
		case "lnHeight":
			z.LockedNeoHeight, err = dc.ReadUint32()
			if err != nil {
				return
			}
		case "leHash":
			z.LockedEthHash, err = dc.ReadString()
			if err != nil {
				return
			}
		case "leHeight":
			z.LockedEthHeight, err = dc.ReadUint32()
			if err != nil {
				return
			}
		case "unHash":
			z.UnlockedNeoHash, err = dc.ReadString()
			if err != nil {
				return
			}
		case "unHeight":
			z.UnlockedNeoHeight, err = dc.ReadUint32()
			if err != nil {
				return
			}
		case "ueHash":
			z.UnlockedEthHash, err = dc.ReadString()
			if err != nil {
				return
			}
		case "ueHeight":
			z.UnlockedEthHeight, err = dc.ReadUint32()
			if err != nil {
				return
			}
		case "neoTimerInterval":
			z.NeoTimerInterval, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "ethTimerInterval":
			z.EthTimerInterval, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "neoUserAddr":
			z.NeoUserAddr, err = dc.ReadString()
			if err != nil {
				return
			}
		case "ethUserAddr":
			z.EthUserAddr, err = dc.ReadString()
			if err != nil {
				return
			}
		case "gasPrice":
			z.GasPrice, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "startTime":
			z.StartTime, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "lastModifyTime":
			z.LastModifyTime, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "neoTimeout":
			z.NeoTimeout, err = dc.ReadBool()
			if err != nil {
				return
			}
		case "ethTimeout":
			z.EthTimeout, err = dc.ReadBool()
			if err != nil {
				return
			}
		case "fail":
			z.Fail, err = dc.ReadBool()
			if err != nil {
				return
			}
		case "remark":
			z.Remark, err = dc.ReadString()
			if err != nil {
				return
			}
		case "interruption":
			z.Interruption, err = dc.ReadBool()
			if err != nil {
				return
			}
		case "deleted":
			err = z.Deleted.DecodeMsg(dc)
			if err != nil {
				return
			}
		case "deletedTime":
			z.DeletedTime, err = dc.ReadInt64()
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *LockerInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 26
	// write "state"
	err = en.Append(0xde, 0x0, 0x1a, 0xa5, 0x73, 0x74, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = z.State.EncodeMsg(en)
	if err != nil {
		return
	}
	// write "rHash"
	err = en.Append(0xa5, 0x72, 0x48, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.RHash)
	if err != nil {
		return
	}
	// write "rOrigin"
	err = en.Append(0xa7, 0x72, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.ROrigin)
	if err != nil {
		return
	}
	// write "amount"
	err = en.Append(0xa6, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Amount)
	if err != nil {
		return
	}
	// write "lnHash"
	err = en.Append(0xa6, 0x6c, 0x6e, 0x48, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.LockedNeoHash)
	if err != nil {
		return
	}
	// write "lnHeight"
	err = en.Append(0xa8, 0x6c, 0x6e, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.LockedNeoHeight)
	if err != nil {
		return
	}
	// write "leHash"
	err = en.Append(0xa6, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.LockedEthHash)
	if err != nil {
		return
	}
	// write "leHeight"
	err = en.Append(0xa8, 0x6c, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.LockedEthHeight)
	if err != nil {
		return
	}
	// write "unHash"
	err = en.Append(0xa6, 0x75, 0x6e, 0x48, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.UnlockedNeoHash)
	if err != nil {
		return
	}
	// write "unHeight"
	err = en.Append(0xa8, 0x75, 0x6e, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.UnlockedNeoHeight)
	if err != nil {
		return
	}
	// write "ueHash"
	err = en.Append(0xa6, 0x75, 0x65, 0x48, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.UnlockedEthHash)
	if err != nil {
		return
	}
	// write "ueHeight"
	err = en.Append(0xa8, 0x75, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.UnlockedEthHeight)
	if err != nil {
		return
	}
	// write "neoTimerInterval"
	err = en.Append(0xb0, 0x6e, 0x65, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.NeoTimerInterval)
	if err != nil {
		return
	}
	// write "ethTimerInterval"
	err = en.Append(0xb0, 0x65, 0x74, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.EthTimerInterval)
	if err != nil {
		return
	}
	// write "neoUserAddr"
	err = en.Append(0xab, 0x6e, 0x65, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.NeoUserAddr)
	if err != nil {
		return
	}
	// write "ethUserAddr"
	err = en.Append(0xab, 0x65, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.EthUserAddr)
	if err != nil {
		return
	}
	// write "gasPrice"
	err = en.Append(0xa8, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.GasPrice)
	if err != nil {
		return
	}
	// write "startTime"
	err = en.Append(0xa9, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.StartTime)
	if err != nil {
		return
	}
	// write "lastModifyTime"
	err = en.Append(0xae, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x54, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.LastModifyTime)
	if err != nil {
		return
	}
	// write "neoTimeout"
	err = en.Append(0xaa, 0x6e, 0x65, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74)
	if err != nil {
		return
	}
	err = en.WriteBool(z.NeoTimeout)
	if err != nil {
		return
	}
	// write "ethTimeout"
	err = en.Append(0xaa, 0x65, 0x74, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74)
	if err != nil {
		return
	}
	err = en.WriteBool(z.EthTimeout)
	if err != nil {
		return
	}
	// write "fail"
	err = en.Append(0xa4, 0x66, 0x61, 0x69, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Fail)
	if err != nil {
		return
	}
	// write "remark"
	err = en.Append(0xa6, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteString(z.Remark)
	if err != nil {
		return
	}
	// write "interruption"
	err = en.Append(0xac, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x75, 0x70, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Interruption)
	if err != nil {
		return
	}
	// write "deleted"
	err = en.Append(0xa7, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64)
	if err != nil {
		return
	}
	err = z.Deleted.EncodeMsg(en)
	if err != nil {
		return
	}
	// write "deletedTime"
	err = en.Append(0xab, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.DeletedTime)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *LockerInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 26
	// string "state"
	o = append(o, 0xde, 0x0, 0x1a, 0xa5, 0x73, 0x74, 0x61, 0x74, 0x65)
	o, err = z.State.MarshalMsg(o)
	if err != nil {
		return
	}
	// string "rHash"
	o = append(o, 0xa5, 0x72, 0x48, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.RHash)
	// string "rOrigin"
	o = append(o, 0xa7, 0x72, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e)
	o = msgp.AppendString(o, z.ROrigin)
	// string "amount"
	o = append(o, 0xa6, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendInt64(o, z.Amount)
	// string "lnHash"
	o = append(o, 0xa6, 0x6c, 0x6e, 0x48, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.LockedNeoHash)
	// string "lnHeight"
	o = append(o, 0xa8, 0x6c, 0x6e, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74)
	o = msgp.AppendUint32(o, z.LockedNeoHeight)
	// string "leHash"
	o = append(o, 0xa6, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.LockedEthHash)
	// string "leHeight"
	o = append(o, 0xa8, 0x6c, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74)
	o = msgp.AppendUint32(o, z.LockedEthHeight)
	// string "unHash"
	o = append(o, 0xa6, 0x75, 0x6e, 0x48, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.UnlockedNeoHash)
	// string "unHeight"
	o = append(o, 0xa8, 0x75, 0x6e, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74)
	o = msgp.AppendUint32(o, z.UnlockedNeoHeight)
	// string "ueHash"
	o = append(o, 0xa6, 0x75, 0x65, 0x48, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.UnlockedEthHash)
	// string "ueHeight"
	o = append(o, 0xa8, 0x75, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74)
	o = msgp.AppendUint32(o, z.UnlockedEthHeight)
	// string "neoTimerInterval"
	o = append(o, 0xb0, 0x6e, 0x65, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c)
	o = msgp.AppendInt64(o, z.NeoTimerInterval)
	// string "ethTimerInterval"
	o = append(o, 0xb0, 0x65, 0x74, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c)
	o = msgp.AppendInt64(o, z.EthTimerInterval)
	// string "neoUserAddr"
	o = append(o, 0xab, 0x6e, 0x65, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72)
	o = msgp.AppendString(o, z.NeoUserAddr)
	// string "ethUserAddr"
	o = append(o, 0xab, 0x65, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72)
	o = msgp.AppendString(o, z.EthUserAddr)
	// string "gasPrice"
	o = append(o, 0xa8, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65)
	o = msgp.AppendInt64(o, z.GasPrice)
	// string "startTime"
	o = append(o, 0xa9, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65)
	o = msgp.AppendInt64(o, z.StartTime)
	// string "lastModifyTime"
	o = append(o, 0xae, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x54, 0x69, 0x6d, 0x65)
	o = msgp.AppendInt64(o, z.LastModifyTime)
	// string "neoTimeout"
	o = append(o, 0xaa, 0x6e, 0x65, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74)
	o = msgp.AppendBool(o, z.NeoTimeout)
	// string "ethTimeout"
	o = append(o, 0xaa, 0x65, 0x74, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74)
	o = msgp.AppendBool(o, z.EthTimeout)
	// string "fail"
	o = append(o, 0xa4, 0x66, 0x61, 0x69, 0x6c)
	o = msgp.AppendBool(o, z.Fail)
	// string "remark"
	o = append(o, 0xa6, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b)
	o = msgp.AppendString(o, z.Remark)
	// string "interruption"
	o = append(o, 0xac, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x75, 0x70, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendBool(o, z.Interruption)
	// string "deleted"
	o = append(o, 0xa7, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64)
	o, err = z.Deleted.MarshalMsg(o)
	if err != nil {
		return
	}
	// string "deletedTime"
	o = append(o, 0xab, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65)
	o = msgp.AppendInt64(o, z.DeletedTime)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *LockerInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			return
		}
		switch msgp.UnsafeString(field) {
		case "state":
			bts, err = z.State.UnmarshalMsg(bts)
			if err != nil {
				return
			}
		case "rHash":
			z.RHash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		case "rOrigin":
			z.ROrigin, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		case "amount":
			z.Amount, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				return
			}
		case "lnHash":
			z.LockedNeoHash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		case "lnHeight":
			z.LockedNeoHeight, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				return
			}
		case "leHash":
			z.LockedEthHash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		case "leHeight":
			z.LockedEthHeight, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				return
			}
		case "unHash":
			z.UnlockedNeoHash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		case "unHeight":
			z.UnlockedNeoHeight, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				return
			}
		case "ueHash":
			z.UnlockedEthHash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		case "ueHeight":
			z.UnlockedEthHeight, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				return
			}
		case "neoTimerInterval":
			z.NeoTimerInterval, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				return
			}
		case "ethTimerInterval":
			z.EthTimerInterval, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				return
			}
		case "neoUserAddr":
			z.NeoUserAddr, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		case "ethUserAddr":
			z.EthUserAddr, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		case "gasPrice":
			z.GasPrice, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				return
			}
		case "startTime":
			z.StartTime, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				return
			}
		case "lastModifyTime":
			z.LastModifyTime, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				return
			}
		case "neoTimeout":
			z.NeoTimeout, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				return
			}
		case "ethTimeout":
			z.EthTimeout, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				return
			}
		case "fail":
			z.Fail, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				return
			}
		case "remark":
			z.Remark, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		case "interruption":
			z.Interruption, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				return
			}
		case "deleted":
			bts, err = z.Deleted.UnmarshalMsg(bts)
			if err != nil {
				return
			}
		case "deletedTime":
			z.DeletedTime, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LockerInfo) Msgsize() (s int) {
	s = 3 + 6 + z.State.Msgsize() + 6 + msgp.StringPrefixSize + len(z.RHash) + 8 + msgp.StringPrefixSize + len(z.ROrigin) + 7 + msgp.Int64Size + 7 + msgp.StringPrefixSize + len(z.LockedNeoHash) + 9 + msgp.Uint32Size + 7 + msgp.StringPrefixSize + len(z.LockedEthHash) + 9 + msgp.Uint32Size + 7 + msgp.StringPrefixSize + len(z.UnlockedNeoHash) + 9 + msgp.Uint32Size + 7 + msgp.StringPrefixSize + len(z.UnlockedEthHash) + 9 + msgp.Uint32Size + 17 + msgp.Int64Size + 17 + msgp.Int64Size + 12 + msgp.StringPrefixSize + len(z.NeoUserAddr) + 12 + msgp.StringPrefixSize + len(z.EthUserAddr) + 9 + msgp.Int64Size + 10 + msgp.Int64Size + 15 + msgp.Int64Size + 11 + msgp.BoolSize + 11 + msgp.BoolSize + 5 + msgp.BoolSize + 7 + msgp.StringPrefixSize + len(z.Remark) + 13 + msgp.BoolSize + 8 + z.Deleted.Msgsize() + 12 + msgp.Int64Size
	return
}
