// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.1
// source: types.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EthContract string `protobuf:"bytes,1,opt,name=ethContract,proto3" json:"ethContract,omitempty"`
	EthAddress  string `protobuf:"bytes,2,opt,name=ethAddress,proto3" json:"ethAddress,omitempty"`
	NeoContract string `protobuf:"bytes,3,opt,name=neoContract,proto3" json:"neoContract,omitempty"`
	NeoAddress  string `protobuf:"bytes,4,opt,name=neoAddress,proto3" json:"neoAddress,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *PingResponse) GetEthContract() string {
	if x != nil {
		return x.EthContract
	}
	return ""
}

func (x *PingResponse) GetEthAddress() string {
	if x != nil {
		return x.EthAddress
	}
	return ""
}

func (x *PingResponse) GetNeoContract() string {
	if x != nil {
		return x.NeoContract
	}
	return ""
}

func (x *PingResponse) GetNeoAddress() string {
	if x != nil {
		return x.NeoAddress
	}
	return ""
}

type DepositLockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nep5TxHash string `protobuf:"bytes,1,opt,name=nep5TxHash,proto3" json:"nep5TxHash,omitempty"`
	Amount     int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	RHash      string `protobuf:"bytes,3,opt,name=rHash,proto3" json:"rHash,omitempty"`
	Addr       string `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *DepositLockRequest) Reset() {
	*x = DepositLockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositLockRequest) ProtoMessage() {}

func (x *DepositLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositLockRequest.ProtoReflect.Descriptor instead.
func (*DepositLockRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *DepositLockRequest) GetNep5TxHash() string {
	if x != nil {
		return x.Nep5TxHash
	}
	return ""
}

func (x *DepositLockRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepositLockRequest) GetRHash() string {
	if x != nil {
		return x.RHash
	}
	return ""
}

func (x *DepositLockRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type FetchNoticeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RHash      string `protobuf:"bytes,1,opt,name=rHash,proto3" json:"rHash,omitempty"`
	Nep5TxHash string `protobuf:"bytes,2,opt,name=nep5TxHash,proto3" json:"nep5TxHash,omitempty"`
}

func (x *FetchNoticeRequest) Reset() {
	*x = FetchNoticeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchNoticeRequest) ProtoMessage() {}

func (x *FetchNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchNoticeRequest.ProtoReflect.Descriptor instead.
func (*FetchNoticeRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *FetchNoticeRequest) GetRHash() string {
	if x != nil {
		return x.RHash
	}
	return ""
}

func (x *FetchNoticeRequest) GetNep5TxHash() string {
	if x != nil {
		return x.Nep5TxHash
	}
	return ""
}

type WithdrawUnlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nep5TxHash string `protobuf:"bytes,1,opt,name=nep5TxHash,proto3" json:"nep5TxHash,omitempty"`
	ROrigin    string `protobuf:"bytes,2,opt,name=rOrigin,proto3" json:"rOrigin,omitempty"`
	RHash      string `protobuf:"bytes,3,opt,name=rHash,proto3" json:"rHash,omitempty"`
}

func (x *WithdrawUnlockRequest) Reset() {
	*x = WithdrawUnlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawUnlockRequest) ProtoMessage() {}

func (x *WithdrawUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawUnlockRequest.ProtoReflect.Descriptor instead.
func (*WithdrawUnlockRequest) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *WithdrawUnlockRequest) GetNep5TxHash() string {
	if x != nil {
		return x.Nep5TxHash
	}
	return ""
}

func (x *WithdrawUnlockRequest) GetROrigin() string {
	if x != nil {
		return x.ROrigin
	}
	return ""
}

func (x *WithdrawUnlockRequest) GetRHash() string {
	if x != nil {
		return x.RHash
	}
	return ""
}

type EventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State    int64  `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	StateStr string `protobuf:"bytes,2,opt,name=stateStr,proto3" json:"stateStr,omitempty"`
	RHash    string `protobuf:"bytes,3,opt,name=rHash,proto3" json:"rHash,omitempty"`
	TxHash   string `protobuf:"bytes,4,opt,name=txHash,proto3" json:"txHash,omitempty"`
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *EventResponse) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *EventResponse) GetStateStr() string {
	if x != nil {
		return x.StateStr
	}
	return ""
}

func (x *EventResponse) GetRHash() string {
	if x != nil {
		return x.RHash
	}
	return ""
}

func (x *EventResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type LockerStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State               int64  `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	StateStr            string `protobuf:"bytes,2,opt,name=stateStr,proto3" json:"stateStr,omitempty"`
	RHash               string `protobuf:"bytes,3,opt,name=rHash,proto3" json:"rHash,omitempty"`
	ROrigin             string `protobuf:"bytes,4,opt,name=rOrigin,proto3" json:"rOrigin,omitempty"`
	Amount              int64  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	UserErc20Addr       string `protobuf:"bytes,6,opt,name=userErc20Addr,proto3" json:"userErc20Addr,omitempty"`
	UserNep5Addr        string `protobuf:"bytes,7,opt,name=userNep5Addr,proto3" json:"userNep5Addr,omitempty"`
	LockedNep5Hash      string `protobuf:"bytes,8,opt,name=lockedNep5Hash,proto3" json:"lockedNep5Hash,omitempty"`
	LockedNep5Height    uint32 `protobuf:"varint,9,opt,name=lockedNep5Height,proto3" json:"lockedNep5Height,omitempty"`
	LockedErc20Hash     string `protobuf:"bytes,10,opt,name=lockedErc20Hash,proto3" json:"lockedErc20Hash,omitempty"`
	LockedErc20Height   uint32 `protobuf:"varint,11,opt,name=lockedErc20Height,proto3" json:"lockedErc20Height,omitempty"`
	UnlockedNep5Hash    string `protobuf:"bytes,12,opt,name=unlockedNep5Hash,proto3" json:"unlockedNep5Hash,omitempty"`
	UnlockedNep5Height  uint32 `protobuf:"varint,13,opt,name=unlockedNep5Height,proto3" json:"unlockedNep5Height,omitempty"`
	UnlockedErc20Hash   string `protobuf:"bytes,14,opt,name=unlockedErc20Hash,proto3" json:"unlockedErc20Hash,omitempty"`
	UnlockedErc20Height uint32 `protobuf:"varint,15,opt,name=unlockedErc20Height,proto3" json:"unlockedErc20Height,omitempty"`
}

func (x *LockerStateResponse) Reset() {
	*x = LockerStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockerStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockerStateResponse) ProtoMessage() {}

func (x *LockerStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockerStateResponse.ProtoReflect.Descriptor instead.
func (*LockerStateResponse) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *LockerStateResponse) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *LockerStateResponse) GetStateStr() string {
	if x != nil {
		return x.StateStr
	}
	return ""
}

func (x *LockerStateResponse) GetRHash() string {
	if x != nil {
		return x.RHash
	}
	return ""
}

func (x *LockerStateResponse) GetROrigin() string {
	if x != nil {
		return x.ROrigin
	}
	return ""
}

func (x *LockerStateResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LockerStateResponse) GetUserErc20Addr() string {
	if x != nil {
		return x.UserErc20Addr
	}
	return ""
}

func (x *LockerStateResponse) GetUserNep5Addr() string {
	if x != nil {
		return x.UserNep5Addr
	}
	return ""
}

func (x *LockerStateResponse) GetLockedNep5Hash() string {
	if x != nil {
		return x.LockedNep5Hash
	}
	return ""
}

func (x *LockerStateResponse) GetLockedNep5Height() uint32 {
	if x != nil {
		return x.LockedNep5Height
	}
	return 0
}

func (x *LockerStateResponse) GetLockedErc20Hash() string {
	if x != nil {
		return x.LockedErc20Hash
	}
	return ""
}

func (x *LockerStateResponse) GetLockedErc20Height() uint32 {
	if x != nil {
		return x.LockedErc20Height
	}
	return 0
}

func (x *LockerStateResponse) GetUnlockedNep5Hash() string {
	if x != nil {
		return x.UnlockedNep5Hash
	}
	return ""
}

func (x *LockerStateResponse) GetUnlockedNep5Height() uint32 {
	if x != nil {
		return x.UnlockedNep5Height
	}
	return 0
}

func (x *LockerStateResponse) GetUnlockedErc20Hash() string {
	if x != nil {
		return x.UnlockedErc20Hash
	}
	return ""
}

func (x *LockerStateResponse) GetUnlockedErc20Height() uint32 {
	if x != nil {
		return x.UnlockedErc20Height
	}
	return 0
}

type Boolean struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Boolean) Reset() {
	*x = Boolean{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Boolean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boolean) ProtoMessage() {}

func (x *Boolean) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boolean.ProtoReflect.Descriptor instead.
func (*Boolean) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *Boolean) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type String struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *String) Reset() {
	*x = String{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *String) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_types_proto protoreflect.FileDescriptor

var file_types_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x92, 0x01, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x65, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x74, 0x68, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x74, 0x68, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x65, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x6f, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x65, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x6f, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x76, 0x0a, 0x12, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4c,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x65,
	0x70, 0x35, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6e, 0x65, 0x70, 0x35, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22, 0x4a, 0x0a, 0x12,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x65, 0x70, 0x35,
	0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65,
	0x70, 0x35, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x22, 0x67, 0x0a, 0x15, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x65, 0x70, 0x35, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x70, 0x35, 0x54, 0x78, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x72, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x48, 0x61, 0x73,
	0x68, 0x22, 0x6f, 0x0a, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x53, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x53, 0x74, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61,
	0x73, 0x68, 0x22, 0xc1, 0x04, 0x0a, 0x13, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x45, 0x72, 0x63, 0x32,
	0x30, 0x41, 0x64, 0x64, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x75, 0x73, 0x65,
	0x72, 0x45, 0x72, 0x63, 0x32, 0x30, 0x41, 0x64, 0x64, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x65, 0x70, 0x35, 0x41, 0x64, 0x64, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x65, 0x70, 0x35, 0x41, 0x64, 0x64, 0x72, 0x12, 0x26,
	0x0a, 0x0e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x4e, 0x65, 0x70, 0x35, 0x48, 0x61, 0x73, 0x68,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x4e, 0x65,
	0x70, 0x35, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2a, 0x0a, 0x10, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64,
	0x4e, 0x65, 0x70, 0x35, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x10, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x4e, 0x65, 0x70, 0x35, 0x48, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x45, 0x72, 0x63, 0x32,
	0x30, 0x48, 0x61, 0x73, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x45, 0x72, 0x63, 0x32, 0x30, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2c, 0x0a, 0x11,
	0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x45, 0x72, 0x63, 0x32, 0x30, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x45,
	0x72, 0x63, 0x32, 0x30, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x75, 0x6e,
	0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x4e, 0x65, 0x70, 0x35, 0x48, 0x61, 0x73, 0x68, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x4e, 0x65,
	0x70, 0x35, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2e, 0x0a, 0x12, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b,
	0x65, 0x64, 0x4e, 0x65, 0x70, 0x35, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x12, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x4e, 0x65, 0x70, 0x35,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b,
	0x65, 0x64, 0x45, 0x72, 0x63, 0x32, 0x30, 0x48, 0x61, 0x73, 0x68, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x11, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x45, 0x72, 0x63, 0x32, 0x30,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x30, 0x0a, 0x13, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64,
	0x45, 0x72, 0x63, 0x32, 0x30, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x13, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x45, 0x72, 0x63, 0x32, 0x30,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x1f, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1e, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xb4, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x41, 0x50, 0x49, 0x12, 0x4b, 0x0a, 0x04, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4c, 0x6f,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x12, 0x22, 0x0d, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2f, 0x6c, 0x6f, 0x63, 0x6b,
	0x3a, 0x01, 0x2a, 0x12, 0x59, 0x0a, 0x0b, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4e, 0x6f, 0x74, 0x69,
	0x63, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x22, 0x1f, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x19, 0x22, 0x14, 0x2f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x2f,
	0x66, 0x65, 0x74, 0x63, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x3a, 0x01, 0x2a, 0x32, 0x62,
	0x0a, 0x0b, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x41, 0x50, 0x49, 0x12, 0x53, 0x0a,
	0x06, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f,
	0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x22, 0x10, 0x2f,
	0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2f, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x3a,
	0x01, 0x2a, 0x32, 0x59, 0x0a, 0x08, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x41, 0x50, 0x49, 0x12, 0x4d,
	0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c, 0x2f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x30, 0x01, 0x32, 0xaa, 0x01,
	0x0a, 0x08, 0x44, 0x65, 0x62, 0x75, 0x67, 0x41, 0x50, 0x49, 0x12, 0x48, 0x0a, 0x04, 0x50, 0x69,
	0x6e, 0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x12, 0x0b, 0x2f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x2f,
	0x70, 0x69, 0x6e, 0x67, 0x12, 0x54, 0x0a, 0x0b, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x2f, 0x6c,
	0x6f, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData = file_types_proto_rawDesc
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_proto_rawDescData)
	})
	return file_types_proto_rawDescData
}

var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_types_proto_goTypes = []interface{}{
	(*PingResponse)(nil),          // 0: proto.PingResponse
	(*DepositLockRequest)(nil),    // 1: proto.DepositLockRequest
	(*FetchNoticeRequest)(nil),    // 2: proto.FetchNoticeRequest
	(*WithdrawUnlockRequest)(nil), // 3: proto.WithdrawUnlockRequest
	(*EventResponse)(nil),         // 4: proto.EventResponse
	(*LockerStateResponse)(nil),   // 5: proto.LockerStateResponse
	(*Boolean)(nil),               // 6: proto.Boolean
	(*String)(nil),                // 7: proto.String
	(*empty.Empty)(nil),           // 8: google.protobuf.Empty
}
var file_types_proto_depIdxs = []int32{
	1, // 0: proto.DepositAPI.Lock:input_type -> proto.DepositLockRequest
	2, // 1: proto.DepositAPI.FetchNotice:input_type -> proto.FetchNoticeRequest
	3, // 2: proto.WithdrawAPI.Unlock:input_type -> proto.WithdrawUnlockRequest
	8, // 3: proto.EventAPI.Event:input_type -> google.protobuf.Empty
	8, // 4: proto.DebugAPI.Ping:input_type -> google.protobuf.Empty
	7, // 5: proto.DebugAPI.LockerState:input_type -> proto.String
	6, // 6: proto.DepositAPI.Lock:output_type -> proto.Boolean
	6, // 7: proto.DepositAPI.FetchNotice:output_type -> proto.Boolean
	6, // 8: proto.WithdrawAPI.Unlock:output_type -> proto.Boolean
	4, // 9: proto.EventAPI.Event:output_type -> proto.EventResponse
	0, // 10: proto.DebugAPI.Ping:output_type -> proto.PingResponse
	5, // 11: proto.DebugAPI.LockerState:output_type -> proto.LockerStateResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositLockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchNoticeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawUnlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockerStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Boolean); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*String); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_rawDesc = nil
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DepositAPIClient is the client API for DepositAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DepositAPIClient interface {
	Lock(ctx context.Context, in *DepositLockRequest, opts ...grpc.CallOption) (*Boolean, error)
	FetchNotice(ctx context.Context, in *FetchNoticeRequest, opts ...grpc.CallOption) (*Boolean, error)
}

type depositAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewDepositAPIClient(cc grpc.ClientConnInterface) DepositAPIClient {
	return &depositAPIClient{cc}
}

func (c *depositAPIClient) Lock(ctx context.Context, in *DepositLockRequest, opts ...grpc.CallOption) (*Boolean, error) {
	out := new(Boolean)
	err := c.cc.Invoke(ctx, "/proto.DepositAPI/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositAPIClient) FetchNotice(ctx context.Context, in *FetchNoticeRequest, opts ...grpc.CallOption) (*Boolean, error) {
	out := new(Boolean)
	err := c.cc.Invoke(ctx, "/proto.DepositAPI/FetchNotice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepositAPIServer is the server API for DepositAPI service.
type DepositAPIServer interface {
	Lock(context.Context, *DepositLockRequest) (*Boolean, error)
	FetchNotice(context.Context, *FetchNoticeRequest) (*Boolean, error)
}

// UnimplementedDepositAPIServer can be embedded to have forward compatible implementations.
type UnimplementedDepositAPIServer struct {
}

func (*UnimplementedDepositAPIServer) Lock(context.Context, *DepositLockRequest) (*Boolean, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (*UnimplementedDepositAPIServer) FetchNotice(context.Context, *FetchNoticeRequest) (*Boolean, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchNotice not implemented")
}

func RegisterDepositAPIServer(s *grpc.Server, srv DepositAPIServer) {
	s.RegisterService(&_DepositAPI_serviceDesc, srv)
}

func _DepositAPI_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositAPIServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DepositAPI/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositAPIServer).Lock(ctx, req.(*DepositLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositAPI_FetchNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchNoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositAPIServer).FetchNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DepositAPI/FetchNotice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositAPIServer).FetchNotice(ctx, req.(*FetchNoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DepositAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DepositAPI",
	HandlerType: (*DepositAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lock",
			Handler:    _DepositAPI_Lock_Handler,
		},
		{
			MethodName: "FetchNotice",
			Handler:    _DepositAPI_FetchNotice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types.proto",
}

// WithdrawAPIClient is the client API for WithdrawAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WithdrawAPIClient interface {
	Unlock(ctx context.Context, in *WithdrawUnlockRequest, opts ...grpc.CallOption) (*Boolean, error)
}

type withdrawAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewWithdrawAPIClient(cc grpc.ClientConnInterface) WithdrawAPIClient {
	return &withdrawAPIClient{cc}
}

func (c *withdrawAPIClient) Unlock(ctx context.Context, in *WithdrawUnlockRequest, opts ...grpc.CallOption) (*Boolean, error) {
	out := new(Boolean)
	err := c.cc.Invoke(ctx, "/proto.WithdrawAPI/Unlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WithdrawAPIServer is the server API for WithdrawAPI service.
type WithdrawAPIServer interface {
	Unlock(context.Context, *WithdrawUnlockRequest) (*Boolean, error)
}

// UnimplementedWithdrawAPIServer can be embedded to have forward compatible implementations.
type UnimplementedWithdrawAPIServer struct {
}

func (*UnimplementedWithdrawAPIServer) Unlock(context.Context, *WithdrawUnlockRequest) (*Boolean, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlock not implemented")
}

func RegisterWithdrawAPIServer(s *grpc.Server, srv WithdrawAPIServer) {
	s.RegisterService(&_WithdrawAPI_serviceDesc, srv)
}

func _WithdrawAPI_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawUnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawAPIServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WithdrawAPI/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawAPIServer).Unlock(ctx, req.(*WithdrawUnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WithdrawAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WithdrawAPI",
	HandlerType: (*WithdrawAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unlock",
			Handler:    _WithdrawAPI_Unlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types.proto",
}

// EventAPIClient is the client API for EventAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventAPIClient interface {
	Event(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (EventAPI_EventClient, error)
}

type eventAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewEventAPIClient(cc grpc.ClientConnInterface) EventAPIClient {
	return &eventAPIClient{cc}
}

func (c *eventAPIClient) Event(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (EventAPI_EventClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EventAPI_serviceDesc.Streams[0], "/proto.EventAPI/Event", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventAPIEventClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EventAPI_EventClient interface {
	Recv() (*EventResponse, error)
	grpc.ClientStream
}

type eventAPIEventClient struct {
	grpc.ClientStream
}

func (x *eventAPIEventClient) Recv() (*EventResponse, error) {
	m := new(EventResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EventAPIServer is the server API for EventAPI service.
type EventAPIServer interface {
	Event(*empty.Empty, EventAPI_EventServer) error
}

// UnimplementedEventAPIServer can be embedded to have forward compatible implementations.
type UnimplementedEventAPIServer struct {
}

func (*UnimplementedEventAPIServer) Event(*empty.Empty, EventAPI_EventServer) error {
	return status.Errorf(codes.Unimplemented, "method Event not implemented")
}

func RegisterEventAPIServer(s *grpc.Server, srv EventAPIServer) {
	s.RegisterService(&_EventAPI_serviceDesc, srv)
}

func _EventAPI_Event_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventAPIServer).Event(m, &eventAPIEventServer{stream})
}

type EventAPI_EventServer interface {
	Send(*EventResponse) error
	grpc.ServerStream
}

type eventAPIEventServer struct {
	grpc.ServerStream
}

func (x *eventAPIEventServer) Send(m *EventResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _EventAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EventAPI",
	HandlerType: (*EventAPIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Event",
			Handler:       _EventAPI_Event_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "types.proto",
}

// DebugAPIClient is the client API for DebugAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DebugAPIClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PingResponse, error)
	LockerState(ctx context.Context, in *String, opts ...grpc.CallOption) (*LockerStateResponse, error)
}

type debugAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewDebugAPIClient(cc grpc.ClientConnInterface) DebugAPIClient {
	return &debugAPIClient{cc}
}

func (c *debugAPIClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/proto.DebugAPI/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugAPIClient) LockerState(ctx context.Context, in *String, opts ...grpc.CallOption) (*LockerStateResponse, error) {
	out := new(LockerStateResponse)
	err := c.cc.Invoke(ctx, "/proto.DebugAPI/LockerState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DebugAPIServer is the server API for DebugAPI service.
type DebugAPIServer interface {
	Ping(context.Context, *empty.Empty) (*PingResponse, error)
	LockerState(context.Context, *String) (*LockerStateResponse, error)
}

// UnimplementedDebugAPIServer can be embedded to have forward compatible implementations.
type UnimplementedDebugAPIServer struct {
}

func (*UnimplementedDebugAPIServer) Ping(context.Context, *empty.Empty) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedDebugAPIServer) LockerState(context.Context, *String) (*LockerStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockerState not implemented")
}

func RegisterDebugAPIServer(s *grpc.Server, srv DebugAPIServer) {
	s.RegisterService(&_DebugAPI_serviceDesc, srv)
}

func _DebugAPI_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugAPIServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DebugAPI/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugAPIServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DebugAPI_LockerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugAPIServer).LockerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DebugAPI/LockerState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugAPIServer).LockerState(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

var _DebugAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DebugAPI",
	HandlerType: (*DebugAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _DebugAPI_Ping_Handler,
		},
		{
			MethodName: "LockerState",
			Handler:    _DebugAPI_LockerState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types.proto",
}
